project_id = "ikvpkjbextmtjnszjexp"

[functions.check-firmware-updates]
verify_jwt = false

[functions.update-miner-firmware]
verify_jwt = false

[functions.fetch-miner-stats]
verify_jwt = false

[functions.fetch-bitaxe-stats]
verify_jwt = false

[functions.fetch-bitcoin-stats]
verify_jwt = false

[functions.setup-influxdb]
verify_jwt = false

[functions.receive-miner-data]
verify_jwt = false

[functions.fetch-influx-stats]
verify_jwt = false

[functions.fetch-altcoin-stats]
verify_jwt = false


[functions.pool-stats-api]
verify_jwt = false
