// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbuwdidbotodwpkaieln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidXdkaWRib3RvZHdwa2FpZWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTY5MjUsImV4cCI6MjA3MjI5MjkyNX0.oq_guBhICmC7E2HYfLE8g7i7ouFN0dEEdDMyqIFs1HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});